# Generated by Django 4.1.5 on 2023-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("specialty", models.CharField(max_length=100)),
                ("about", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
