# Generated by Django 4.1.5 on 2023-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MeHealth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="doctor_profile/"),
        ),
    ]
